version: "3.5"
services:
  db:
    image: postgis/postgis
    container_name: qol_maas_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: satreps2023
    ports:
      - "6732:5432"
